In [84]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (1.4.3)
Requirement already satisfied: pytz>=2020.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.18.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from pandas) (1.23.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [89]:
import sqlite3
import gzip

'''
sqlite_doc = gzip.open('data-mysqlite/eicu_v2_0_1.sqlite3.gz', 'rb')
file_content = sqlite_doc.read()
'''
data = gzip.GzipFile('data-mysqlite/eicu_v2_0_1.sqlite3.gz','r')
d = data.read()

con = sqlite3.connect(d)

cur = con.cursor()

ValueError: embedded null byte

In [88]:
patients = cur.execute('''SELECT * FROM patient''')
patients_cols = list(map(lambda x: x[0], cur.description))
patients = pd.DataFrame(patients, columns=patients_cols)
patients

DatabaseError: file is not a database

In [35]:
patients_int = ['patientunitstayid', 'gender', 'age', 'ethnicity', 'hospitalid', 'admissionheight', 'hospitaladmitsource', 'hospitaldischargelocation', 'unittype', 'unitadmitsource','admissionweight']
input_information = patients[patients_int]
input_information

,patientunitstayid,gender,age,ethnicity,hospitalid,admissionheight,hospitaladmitsource,hospitaldischargelocation,unittype,unitadmitsource,admissionweight
0,141764,Female,87,Caucasian,59,157.5,,Home,Med-Surg ICU,ICU to SDU,
1,141765,Female,87,Caucasian,59,157.5,,Home,Med-Surg ICU,Emergency Department,46.5
2,143870,Male,76,Caucasian,68,167,Operating Room,Home,SICU,Operating Room,77.5
3,144815,Female,34,Caucasian,56,172.7,Emergency Department,Other Hospital,Med-Surg ICU,Emergency Department,60.3
4,145427,Male,61,Caucasian,68,177.8,Emergency Department,Home,SICU,Operating Room,91.7
...,...,...,...,...,...,...,...,...,...,...,...
2515,3351763,Female,62,Caucasian,459,165.1,Operating Room,Home,Med-Surg ICU,Operating Room,134.5
2516,3352230,Male,41,African American,458,177.8,Direct Admit,Home,CTICU,Operating Room,127
2517,3352231,Male,41,African American,458,177.8,Direct Admit,Home,Cardiac ICU,Direct Admit,127
2518,3352333,Male,72,Caucasian,458,177.8,Other Hospital,,SICU,Other Hospital,68.3
2519,3353113,Male,50,Caucasian,459,188,Floor,Home,Med-Surg ICU,Floor,88

In [36]:
hospitals = cur.execute('''SELECT * FROM hospital''')
hospitals_cols = list(map(lambda x: x[0], cur.description))
hospitals = pd.DataFrame(hospitals, columns=hospitals_cols)
hospitals

     hospitalid numbedscategory teachingstatus   region
0            56            <100              f  Midwest
1            58       100 - 249              f  Midwest
2            59            <100              f  Midwest
3            60            <100              f  Midwest
4            61            <100              f  Midwest
..          ...             ...            ...      ...
181         445       100 - 249              f  Midwest
182         449          >= 500              t  Midwest
183         452                              f  Midwest
184         458          >= 500              f    South
185         459       100 - 249              f    South

[186 rows x 4 columns]

In [37]:
input_information = pd.merge(input_information, hospitals, on="hospitalid", how="left")
input_information = input_information.drop('hospitalid', axis=1)
input_information

,patientunitstayid,gender,age,ethnicity,admissionheight,hospitaladmitsource,hospitaldischargelocation,unittype,unitadmitsource,admissionweight,numbedscategory,teachingstatus,region
0,141764,Female,87,Caucasian,157.5,,Home,Med-Surg ICU,ICU to SDU,,<100,f,Midwest
1,141765,Female,87,Caucasian,157.5,,Home,Med-Surg ICU,Emergency Department,46.5,<100,f,Midwest
2,143870,Male,76,Caucasian,167,Operating Room,Home,SICU,Operating Room,77.5,<100,f,Midwest
3,144815,Female,34,Caucasian,172.7,Emergency Department,Other Hospital,Med-Surg ICU,Emergency Department,60.3,<100,f,Midwest
4,145427,Male,61,Caucasian,177.8,Emergency Department,Home,SICU,Operating Room,91.7,<100,f,Midwest
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,3351763,Female,62,Caucasian,165.1,Operating Room,Home,Med-Surg ICU,Operating Room,134.5,100 - 249,f,South
2516,3352230,Male,41,African American,177.8,Direct Admit,Home,CTICU,Operating Room,127,>= 500,f,South
2517,3352231,Male,41,African American,177.8,Direct Admit,Home,Cardiac ICU,Direct Admit,127,>= 500,f,South
2518,3352333,Male,72,Caucasian,177.8,Other Hospital,,SICU,Other Hospital,68.3,>= 500,f,South
2519,3353113,Male,50,Caucasian,188,Floor,Home,Med-Surg ICU,Floor,88,100 - 249,f,South

In [39]:
allergies = cur.execute('''SELECT * FROM allergy''')
allergies_cols = list(map(lambda x: x[0], cur.description))
allergies = pd.DataFrame(allergies, columns=allergies_cols)
allergies

,allergyid,patientunitstayid,allergyoffset,allergyenteredoffset,allergynotetype,specialtytype,usertype,rxincluded,writtenineicu,drugname,allergytype,allergyname,drughiclseqno
0,357144,243097,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,,Non Drug,penicillins,
1,442253,243097,1288,1294,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721
2,357143,243097,2549,2552,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721
3,329929,243097,21,28,Admission,eCM Primary,THC Nurse,True,True,,Non Drug,penicillins,
4,363374,243097,3988,3989,Comprehensive Progress,eCM Primary,THC Nurse,True,True,CODEINE PHOSPHATE,Drug,CODEINE PHOSPHATE,1721
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2470,4192984,3351763,14,51,Admission,eCM Primary,THC Nurse,False,True,,Non Drug,latex,
2471,4222140,3351763,14,51,Admission,eCM Primary,THC Nurse,False,True,LEVAQUIN,Drug,LEVAQUIN,12383
2472,4195996,3353113,77,86,Admission,eCM Primary,THC Nurse,False,True,,Non Drug,Contrast Dye,
2473,4230248,3353113,77,86,Admission,eCM Primary,THC Nurse,False,True,PENICILLIN G BENZATHINE,Drug,PENICILLIN G BENZATHINE,3941
2474,4223181,3353113,77,86,Admission,eCM Primary,THC Nurse,False,True,LISINOPRIL,Drug,LISINOPRIL,132

In [47]:
allergies['allergyname'].unique()

array(['', 'CODEINE PHOSPHATE', 'VALSARTAN', 'HYDROCHLOROTHIAZIDE',
       'ATENOLOL', 'LINEZOLID', 'DULOXETINE HCL', 'VANCOMYCIN',
       'AMOXICILLIN', 'TRIMETHOPRIM', 'SULFAMETHOXAZOLE', 'OXYCODONE HCL',
       'MORPHINE SULFATE', 'ZETIA', 'LIPITOR', 'VYTORIN', 'PHENYTOIN',
       'CARBAMAZEPINE', 'AZITHROMYCIN', 'METOCLOPRAMIDE HCL', 'HALDOL',
       'ASPIRIN', 'VALIUM', 'PENICILLIN G BENZATHINE',
       'PENICILLIN G SODIUM', 'SULFACETAMIDE', 'CODEINE SULFATE',
       'HYDROCODONE BITARTRATE', 'ACETAMINOPHEN', 'IODINE', 'XYLOCAINE',
       'LIDOCAINE', 'FOSAMAX', 'BIAXIN', 'PHENOBARBITAL', 'REGLAN',
       'KEFLEX', 'METHYLPREDNISOLONE', 'MOMETASONE FUROATE', 'NIACIN',
       'TOPROL XL', 'SULFACETAMIDE SODIUM/SULFUR', 'WATERMELON',
       'PENICILLAMINE', 'CELEBREX', 'BUTORPHANOL TARTRATE', 'PERSANTINE',
       'CEFUROXIME', 'LATEX LEG STRAPS', 'LATEX EXTENSION TUBING',
       'LATEX GLOVES', 'CIPRO', 'LEVAQUIN', 'PHENERGAN',
       'METOPROLOL SUCCINATE', 'POVIDONE', 'SOMA', 'AMLODIPINE BESILATE',
       'BACTRIM', 'NEOSPORIN', 'AMBIEN', 'ZOCOR', 'SULFADIAZINE',
       'LISINOPRIL', 'BENADRYL', 'IBUPROFEN', 'NIASPAN', 'ZOLOFT',
       'COREG', 'MOTRIN', 'AMIODARONE HCL', 'MEXILETINE HCL',
       'TETANUS TOXOID ADSORBED', 'NORVASC', 'PRINIVIL', 'TALWIN',
       'OXYCODONE CONCENTRATE', 'SIMVASTATIN', 'ANTIHISTAMINE', 'ZOFRAN',
       'ERYTHROMYCIN', 'NITROFURANTOIN', 'MACROBID', 'NEURONTIN',
       'CARDURA', 'NITROGLYCERIN PATCH', 'ISORDIL', 'VASOTEC',
       'PROCARDIA', 'CLONIDINE', 'DILANTIN', 'CEFOTAXIME SODIUM',
       'DEMEROL', 'CEPHALEXIN', 'PREDNISONE', 'TRAMADOL HCL',
       'PREGABALIN', 'DICLOFENAC SODIUM', 'ENDOCET', 'GLYBURIDE',
       'CIPROFLOXACIN', 'ACTOS', 'BETADINE', 'PANTOPRAZOLE SODIUM',
       'LOVENOX', 'VENTOLIN', 'PENICILLIN G POTASSIUM', 'FENTANYL',
       'ULTRACET', 'TOPAMAX', 'CAFFEINE', 'LEVOFLOXACIN',
       'SULFAMETHOXAZOLE-TRIMETHOPRIM', 'SULFUR', 'DIVALPROEX SODIUM',
       'ATIVAN', 'ZOLPIDEM TARTRATE', 'ARIPIPRAZOLE', 'AMPICILLIN SODIUM',
       'CRESTOR', 'CELECOXIB', 'AZOR', 'HYDROCOD-CPM-PSEUDOEPHEDRINE',
       'FLUTICASONE FUROATE', 'SERTRALINE HCL', 'MS CONTIN', 'LANTUS',
       'ROFLUMILAST', 'ENALAPRIL MALEATE', 'PREDNISOLONE', 'DALIRESP',
       'ROCEPHIN', 'LEXAPRO', 'DOXYCYCLINE CALCIUM',
       'TRIMETHOPRIM-POLYMYXIN B SULF', 'METRONIDAZOLE', 'AUGMENTIN',
       'CYMBALTA', 'IMDUR', 'ALLOPURINOL', 'MEROPENEM', 'COZAAR',
       'SULFAMIDE', 'ATORVASTATIN CALCIUM', 'RABEPRAZOLE SODIUM',
       'HYDROCODONE BIT/ACETAMINOPHEN', 'LANSOPRAZOLE', 'RANITIDINE HCL',
       'MEPERIDINE HCL', 'OMEPRAZOLE', 'CIMETIDINE',
       'ROBITUSSIN COUGH & COLD CF', 'BETHANECHOL CHLORIDE',
       'PAROXETINE HCL', 'ADHESIVE', 'TYLENOL', 'MEMANTINE HCL',
       'CEFAZOLIN', 'MISOPROSTOL', 'CLARITHROMYCIN',
       'DICLOFENAC EPOLAMINE', 'TAMSULOSIN HCL', 'CARBIDOPA-LEVODOPA',
       'AMITRIPTYLINE HCL', 'NEOMYCIN SULFATE',
       'TETANUS IMMUNE GLOBULIN/PF', 'HYDROCODONE BIT-IBUPROFEN',
       'ALBUTEROL', 'NITROGLYCERIN', 'LABETALOL HCL', 'ZOSYN',
       'BENZTROPINE MESYLATE', 'INDOMETHACIN', 'MICARDIS',
       'HEPARIN FLUSH', 'PENICILLIN V POTASSIUM', 'SULFABENZAMIDE',
       'PEANUT BUTTER FLAVOR', 'CARDIZEM', 'HYDRALAZINE HCL',
       'CLINDAMYCIN HCL', 'THEOPHYLLINE', 'ATROPINE', 'SYMBICORT',
       'ISOSORBIDE', 'PIROXICAM', 'METHADONE HCL', 'LYRICA', 'LORTAB',
       'IODIDES', 'OXACILLIN',
       'TETANUS AND DIPHTHERIA TOXOIDS, ADSORBED, ADULT/PF ', 'PROTONIX',
       'ZITHROMAX', 'AVELOX', 'FELDENE', 'KETEK', 'CORTISPORIN',
       'SULFACETAMIDE SODIUM', 'MOXIFLOXACIN HCL', 'SINGULAIR',
       'HYDROCODONE BITARTRATE/ACETAMINOPHEN', 'LODOSYN', 'TUSSIONEX',
       'GUAIFENESIN/PSEUDOEPHEDRINE HCL', 'WELLBUTRIN', 'CLEOCIN',
       'LOSARTAN POTASSIUM', 'QUININE HCL', 'VICODIN', 'MIDAZOLAM',
       'DIMETAPP', 'RIFAMPIN', 'VENLAFAXINE HCL', 'MOBIC', 'PERCOCET',
       'OXYCONTIN', 'ADHESIVE TAPE', 'MAGNESIUM', 'NEXIUM', 'CHANTIX',
       'TENORMIN', 'SYNTHROID', 'ADALAT CC', 'ALTACE', 'DILAUDID',
       'IMITREX', 'AMLODIPINE BES/OLMESARTAN MED', 'RANEXA',
       'CODEINE PHOS', 'ACTONEL', 'BONIVA', 'HEPARIN SODIUM', 'NAPROXEN',
       'LINCOMYCIN HCL', 'TRICOR', 'WELCHOL', 'TRIAMTERENE', 'ZESTRIL',
       'GEMFIBROZIL', 'BENAZEPRIL HCL', 'CEFACLOR', 'NALBUPHINE HCL',
       'NU-COPD', 'ULTRAM', 'KETOROLAC TROMETHAMINE', 'METFORMIN HCL',
       'GABAPENTIN', 'INDOCIN', 'MILRINONE LACTATE', 'BUMETANIDE',
       'PRADAXA', 'NORTRIPTYLINE HCL', 'CAPTOPRIL', 'AVAPRO',
       'FOSINOPRIL SODIUM', 'DIOVAN', 'METHYLDOPA',
       'MILRINONE IN 5% DEXTROSE', 'IRON', 'LESCOL', 'COAL TAR', 'EFUDEX',
       'TETANUS AND DIPHTHERIA TOXOIDS, ADULT',
       'INFLUENZA VACCINE TV SPLIT 2013-14 (18 YR+) CELL DERIVED/PF',
       'AMOXICILLIN/POTASSIUM CLAVULANATE', 'PAXIL', 'SOTALOL', 'LASIX',
       'SULFACETAMIDE SOD MONOHYDRATE', 'OPIUM/BELLADONNA ALKALOIDS',
       'TETRACYCLINE', 'SULFANILAMIDE',
       'CODEINE PHOSPHATE/BUTALBITAL/ASPIRIN/CAFFEINE', 'ASPIR 81',
       'CALCIONATE', 'XANAX', 'MIACALCIN', 'EVISTA',
       'SULFAMETHOXAZOLE/TRIMETHOPRIM', 'IODIXANOL', 'GENTAMICIN SULFATE',
       'FLAGYL', 'ALPRAZOLAM', 'MERCURY AMMONIATED', 'MERBROMIN',
       'ALENDRONATE SODIUM', 'QUINAPRIL HCL', 'THIORIDAZINE HCL',
       'THIMEROSAL', 'WARFARIN SODIUM', 'TICLID', 'PLAVIX',
       'FLUVASTATIN SODIUM', 'ROSUVASTATIN CALCIUM', 'LATEX EXAM GLOVES',
       'ERYTHROMYCIN BASE'], dtype=object)

In [78]:
allergies['num'] = 1
patients_allergies = allergies.pivot_table(index=['patientunitstayid'], 
            columns=['allergyname'], values='num').fillna(0)
patients_allergies

allergyname,"""CAN'T take narcs""",? lasix,? norco / opiates,ACCUPRIL,ACE INHIBITORS,ACE inhibitors,ACE-I,ACETAMINOPHEN,ACTONEL,ACTOS,...,ultram,vioxx,wasp venom,watermelon,wine,zestril,zetia,zithromax,zocor,zolpidem
patientunitstayid,,,,,,,,,,,,,,,,,,,,,
243097,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
244477,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
246997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
249328,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
250073,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3344945,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3347501,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3347502,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3351763,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3353113,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [79]:
# Allergies from the first patient
patients_allergies.loc[243097][patients_allergies.loc[243097]>0]

allergyname
CODEINE PHOSPHATE    1.0
penicillins          1.0
Name: 243097, dtype: float64